### ISSUE TITLE
文档有错误，没有这个接口！

### ISSUE THREAD

**Issue by wwb568109135** [liangfengbo/nodejs-koa2-mysql-sequelize-jwt#1]
比如注册用户接口：在postman软件操作接口，例注册接口：

post 请求

http://localhost:3000/api/v1/createUser?username=梁凤波bo&password=bobo12345
创建成功后返回信息：

{
    "code": 200,
    "message": "创建成功",
    "bean": {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuaigeWHpOazomJvIiwiaWQiOjUsImlhdCI6MTUyNzczNjUzMSwiZXhwIjoxNTI3NzQwMTMxfQ.GAQg-hZm3rDYq70-16sgfNHvD64gmrWSFzQCZQs7bl4"
    }
}

**Comment by liangfengbo** [comment]
您好，接口已经完善了，可以学习啦
