### ISSUE TITLE
上线部署

### ISSUE THREAD

**Issue by lemonwong** [liangfengbo/nodejs-koa2-mysql-sequelize-jwt#2]
老师你好，请问这个项目后台部署上线流程是怎样的 vue项目上线可以npm run build 打包然后把打包的文件放在服务器上，nodejs的后台上线是怎样的流程？第一次接触nodejs，老师有空的时候能帮忙解答下吗。感谢

**Comment by liangfengbo** [comment]
> 老师你好，请问这个项目后台部署上线流程是怎样的 vue项目上线可以npm run build 打包然后把打包的文件放在服务器上，nodejs的后台上线是怎样的流程？第一次接触nodejs，老师有空的时候能帮忙解答下吗。感谢

部署很简单的，使用pm2和Nginx，你可以在服务器上传项目代码，然后在项目的根目录下，使用pm2启动nodejs项目运行；vue项目打包后，使用Nginx执行dist目录即可

**Comment by liangfengbo** [comment]
> 老师你好，请问这个项目后台部署上线流程是怎样的 vue项目上线可以npm run build 打包然后把打包的文件放在服务器上，nodejs的后台上线是怎样的流程？第一次接触nodejs，老师有空的时候能帮忙解答下吗。感谢

帮你找了几遍文章：
pm2启动项目：https://blog.csdn.net/ziwoods/article/details/72833233

vue项目你可能需要学习一下Nginx，就会明白了，如果还有什么不明白可以继续我

**Comment by lemonwong** [comment]
> > 老师你好，请问这个项目后台部署上线流程是怎样的 vue项目上线可以npm run build 打包然后把打包的文件放在服务器上，nodejs的后台上线是怎样的流程？第一次接触nodejs，老师有空的时候能帮忙解答下吗。感谢
> 
> 帮你找了几遍文章：
> pm2启动项目：https://blog.csdn.net/ziwoods/article/details/72833233
> 
> vue项目部署你可能需要学习一下Nginx，就会明白了，如果还有什么不明白可以继续我

多谢 我先看看
