### ISSUE TITLE
sequelize结构

### ISSUE THREAD

**Issue by WuMu2309899048** [liangfengbo/nodejs-koa2-mysql-sequelize-jwt#5]
您好 想问一下关于使用sequelize 中的目录结构   module目录  schema目录
这两个目录作用没有弄清楚啥意思

**Comment by liangfengbo** [comment]
> 您好 想问一下关于使用sequelize 中的目录结构 module目录 schema目录
> 这两个目录作用没有弄清楚啥意思

简单来说schema是建表，module是操作表
